spring:
  application:
    name: dubbo-demo-provider
  cloud:
    # Nacos ??????????
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos ?????

# Dubbo ?????? DubboConfigurationProperties ?
dubbo:
  scan:
    base-packages: com.example.dubbodemoprovider.service # ?? Dubbo ???????????
  # Dubbo ???????????? ProtocolConfig Map
  protocols:
    dubbo:
      name: dubbo # ????
      port: -1 # ?????-1 ???????? 20880 ??
  # Dubbo ??????????? RegistryConfig ?
  registry:
    address: spring-cloud://127.0.0.1:8848 # ?? Dubbo ?????????
  # Spring Cloud Alibaba Dubbo ???????? DubboCloudProperties ?
  cloud:
    subscribed-services: '' # ????????????? * ???????
